### ISSUE TITLE
证书安装失败，请检查您的域名，确保80端口未打开并且未被占用。并在安装完成后，使用选项8修复

### ISSUE THREAD

**Issue by doegeenon** [kirin10000/V2Ray-TLS-Web-setup-script#1]
大神你好，想请教一下这怎么解决，Debian10系统，域名一直用这个，没动过，以前没事的突然报这个，不知道怎么解决

**Comment by kirin10000** [comment]
刚刚重置了一台 debian10 安装，没能复现你的错误。
1.先检查一下域名解析是否正确，看看域名是不是过期了
    使用`nslookup 你的域名`命令，在服务器或者windows的cmd都能运行，如果没有开启cdn，应该能看到域名解析到你的服务器ip上
2.抱歉我的脚本那个地方写错了，因为，应该是`使用选项9修复`，因为之前重置域名选项是选项8，后来选项增加了
3.更新一下脚本`wget -O V2Ray-TLS+Web-setup.sh --no-check-certificate https://github.com/kirin10000/V2Ray-TLS-Web-setup-script/raw/master/V2Ray-TLS+Web-setup.sh`然后运行脚本尝试使用选项9修复，还是提示错误的话就把Log贴出来

**Comment by doegeenon** [comment]
身为一个合格的菜鸟我用了最老土的方法申请新域名重新解析，所有都重新弄一遍就好了，我笑了，应该是域名问题，脚本贼牛逼，谢大神

**Comment by doegeenon** [comment]
哥，想请教你个问题，主要是也不知道能问谁，也没法私信你，也不想新建issue，毕竟只是自己不懂，我想了解下新出的xtls direct我这边想体验一下需要怎么做呢？或者我只需要修改手机端上的设置就行？

**Comment by kirin10000** [comment]
> 哥，想请教你个问题，主要是也不知道能问谁，也没法私信你，也不想新建issue，毕竟只是自己不懂，我想了解下新出的xtls direct我这边想体验一下需要怎么做呢？或者我只需要修改手机端上的设置就行？

脚本在两天前更新了一次，已经支持xtls direct了。目前支持xtls direct的客户端：
   Windows    ：V2RayN  v3.26+
   Android    ：V2RayNG v1.4.8+

**Comment by kirin10000** [comment]
@doegeenon 不清楚已经关闭的issue能不能传达到，所以@一下😂

**Comment by doegeenon** [comment]
> > 哥，想请教你个问题，主要是也不知道能问谁，也没法私信你，也不想新建issue，毕竟只是自己不懂，我想了解下新出的xtls direct我这边想体验一下需要怎么做呢？或者我只需要修改手机端上的设置就行？
> 
> 脚本在两天前更新了一次，已经支持xtls direct了。目前支持xtls direct的客户端：
>    Windows    ：V2RayN  v3.26+
>    Android    ：V2RayNG v1.4.8+

看到了哥😂还真的是@了才收到邮件提醒，谢大腿🙏还有我以后也这样问你吗？还是我留个邮箱你给我扣个1以后有问题我再问你，真的不知道能问谁，当然你觉得不好也无所谓的，还是心存感恩，我邮箱 doegeenon@outlook.com
