### ISSUE TITLE
新的XTLS direct脚本安装成功无错误但配置好无法使用，报错

### ISSUE THREAD

**Issue by doegeenon** [kirin10000/V2Ray-TLS-Web-setup-script#2]
v2rayN（v3.26）报错内容：
 [Warning] [4064141144] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp vpsIP地址:443: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed.

v2ray-core版本4.31.0
v2rayNG也是报错无法识别到网络

**Comment by kirin10000** [comment]
我重置了一台debian10重新安装了一遍，没有发现错误，连接也正常。请检查一下你的客户端配置，和服务端的v2ray是否在运行，以及脚本是不是最新的
