### ISSUE TITLE
dalao，可不可以把自动更新内核并安装BBR的部分单独分出来做成一个脚本......

### ISSUE THREAD

**Issue by kokorobeats** [kirin10000/V2Ray-TLS-Web-setup-script#3]
dalao，可不可以把自动更新内核并安装BBR的部分单独分出来做成一个脚本......这个超有用的诶..........

**Comment by kirin10000** [comment]
一键更新内核脚本已经分离出来了：
https://github.com/kirin10000/update-kernel
其他选项都是整合其它大佬的脚本。
如果你需要，可以自己把更新bbr的部分提取出来做一个脚本，只要在脚本中注明修改自我这个脚本就行

**Comment by kokorobeats** [comment]
谢谢dalao！
